site_name: Neuroshok Generic Language
site_dir: /srv/web/ngl/doc
docs_dir: learn

theme:
    name: readthedocs
    navigation_depth: 0
    highlightjs: false
    include_homepage_in_sidebar: false
    collapse_navigation: false
    titles_only: false